### PR TITLE
Add YouTube logo to footer

### PR DESCRIPTION
**Pull request by OlliMulchandani**
Screenshot 2024-06-03 at 4 09 02 PM
Screenshot 2024-06-03 at 4 09 18 PM

### CODE REVIEW

**Comment by epicfaace** [comment]
Can you add a screenshot in the PR description? @OlliMulchandani

**Comment by OlliMulchandani** [comment]
Done @epicfaace

**Review by epicfaace — APPROVED** [review]
Thanks!

**Review by OlliMulchandani — COMMENTED** [review]
Photo changed
Screenshot 2024-06-04 at 3 19 06 PM

**Comment by epicfaace** [comment]
@OlliMulchandani can you update Kannan's headshot so it's more cropped / doesn't include people in the background?

generally best to keep different tasks in different PRs, that way one issue in one task doesn't impact another issue in another task

**Comment by OlliMulchandani** [comment]
Ok sounds good, I cropped it again. Since I already started this pull request between these two branches, I'm not sure how to create a new one for this separate issue, but for the next one I will separate them. Lmk if there's anything else needed to be done for these two issues before the branches are merged.
image

**Pull request merged**
